app/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

# yapf: disable
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("change-password/", views.ChangePasswordView.as_view(), name="change_password"),
    path("set-new-password/<str:username>/<str:verification_code>", views.SetNewPasswordsView.as_view(), name="set_new_password"),
    path("reset-password/", views.ResetPasswordSendOTPView.as_view(), name="reset_password"),
    path("enter-otp/<str:username>/<str:otp_id>", views.EnterOTPToResetPasswordView.as_view(), name="enter_otp"),

    path("verify-phone", views.VerifyPhoneView.as_view(), name="verify_phone"),
    path("send-otp", views.SendOtp.as_view(), name="send_otp"),
]

app/setup/urls.py
from django.urls import path

from . import views

app_name = "setup"

#yapf: disable
urlpatterns = [
   
]

app/accounts/forms.py
from django import forms
from django.contrib.auth.models import Group

from accounts.models import User


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = [
            'name',
        ]


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            'email_address',
            'phone',
            'locale',
            "phone_network",
            'assigned_image_batch',
            "assigned_audio_batch",
            'surname',
            'other_names',
        ]

app/accounts/views.py
from asyncio.log import logger

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View

from accounts.models import User
from local_voice.utils.functions import get_errors_from_form


class LoginView(View):
    template_name = 'accounts/login.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")
        remember_me = "on" in request.POST.get("remember_me", "")

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            if remember_me:
                request.session.set_expiry(86400 * 30)
            user.last_login_date = timezone.now()
            user.save()
            redirect_url = request.GET.get("next") or "dashboard:index"
            return redirect(redirect_url)
        else:
            context = {k: v for k, v in request.POST.items()}
            messages.warning(request, "Invalid credentials")
            return render(request, self.template_name, context)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('accounts:login')


class ProfileView(View):
    template_name = 'accounts/profile.html'
    # form_class = UserUpdateForm

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, *args, **kwargs):
        """For updating user profile"""
        user_groups = request.user.groups.all()
        request.user.groups.set(user_groups)
        if request.FILES.get("photo"):
            photo = request.FILES.get("photo")
            request.user.photo = photo
            request.user.save()
            messages.success(request, "Profile photo updated")
        else:
            form_class = self.form_class(request.POST, instance=request.user)
            if form_class.is_valid():
                user = form_class.save()
                # Prevent changing of verified phone numbers.
                if user.phone_verified():
                    user.phone = user.verified_phone
                    user.save()
                user.groups.set(user_groups)
                user.save()
                messages.success(request, "Profile updated")
            else:
                logger.error(form_class.errors)
                error = get_errors_from_form(form_class)
                messages.warning(request, error)
        return redirect("accounts:profile")


class ChangePasswordView(View):

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, *args, **kwargs):
        """For changing password"""
        current_password = request.POST.get("current_password")
        new_password = request.POST.get("new_password")
        confirm_password = request.POST.get("confirm_password")
        if new_password == confirm_password:
            if request.user.check_password(current_password):
                request.user.set_password(new_password)
                request.user.save()
                messages.success(request, "Password changed")
            else:
                messages.warning(request, "Invalid old password")
        else:
            messages.warning(request, "Passwords do not match")
        return redirect("accounts:profile")


class VerifyPhoneView(View):
    template_name = 'accounts/verify_phone.html'

    def get(self, request):
        otp = Otp.objects.filter(
            address=request.user.phone).order_by("-created_at").first()
        if not otp or otp.expired():
            messages.warning(request, "No token found.")
            return redirect("dashboard:index")

        context = {
            "otp": otp,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        pin = request.POST.get("pin")
        otp = Otp.objects.filter(
            address=request.user.phone).order_by("-created_at").first()
        if otp and otp.validate(pin):
            request.user.verified_phone = otp.address
            request.user.save()
            otp.delete()
            messages.success(request, "Phone number has been verified.")
            return redirect("accounts:profile")
        else:
            messages.error(request, "Invalid pin")
        return redirect(request.META.get("HTTP_REFERER"))


class SendOtp(View):

    def get(self, request):
        return redirect("dashboard:index")

    def post(self, request, *args, **kwargs):
        otp = Otp.objects.create(address=request.user.phone)
        otp.send_sms()
        return redirect("accounts:verify_phone")


class VerifyApplicationApprovalOTPView(View):
    """For verifying application approval OTP. The OTP was sent via ajax in ajax.py"""

    def get(self, request):
        return redirect("dashboard:index")

    def post(self, request):
        pin = request.POST.get("pin")
        model_name = request.POST.get("model_name")
        application_id = request.POST.get("application_id")
        model_class = get_application_model(model_name)

        if not model_class:
            messages.warning(request, "Invalid model")
            return redirect(request.META.get("HTTP_REFERER"))

        application = model_class.objects.filter(id=application_id).first()
        if not application:
            messages.warning(request, "Application not found.")
            return redirect(request.META.get("HTTP_REFERER"))

        otp = Otp.objects.filter(
            address=request.user.phone).order_by("-created_at").first()
        if otp and otp.validate(pin):
            application.otp_verification_date = timezone.now()
            application.save()
            otp.delete()
            messages.success(request, "OTP verified")
        else:
            messages.error(request, "Invalid pin")
        return redirect(request.META.get("HTTP_REFERER"))


class ResetPasswordSendOTPView(View):
    template_name = 'accounts/reset_password_send_otp.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST.get("username")
        user = User.objects.filter(username=username).first()
        if not user:
            messages.warning(request, "User not found.")
            return redirect(request.META.get("HTTP_REFERER"))
        if not user.phone_verified():
            messages.warning(
                request,
                "Please your phone number was not verified. Kindly contact the administrator to reset your password."
            )
            return redirect(request.META.get("HTTP_REFERER"))

        Otp.objects.filter(address=user.phone).delete()
        otp = Otp.objects.create(address=user.phone)
        sent = otp.send_sms()
        if sent:
            return redirect("accounts:enter_otp", username, otp.id)
        else:
            messages.error(request, "Could not send OTP")
            return redirect(request.META.get("HTTP_REFERER"))


class EnterOTPToResetPasswordView(View):
    template_name = 'accounts/enter_otp.html'

    def get(self, request, username, otp_id):
        otp = Otp.objects.filter(id=otp_id).first()
        if not otp or otp.expired():
            messages.warning(request, "OTP not found.")
            return redirect("accounts:reset_password")
        context = {
            "otp": otp,
            "username": username,
        }
        return render(request, self.template_name, context)

    def post(self, request, username, otp_id):
        pin = request.POST.get("pin")
        otp = Otp.objects.filter(id=otp_id).order_by("-created_at").first()
        if not otp:
            messages.warning(request, "OTP not found.")
            return redirect("accounts:reset_password")

        if otp and otp.validate(pin):
            user = User.objects.filter(username=username).first()
            user.password_reset_verification_code = otp.pin
            user.save()
            otp.delete()
            return redirect("accounts:set_new_password", username, pin)
        else:
            messages.error(request, "Invalid pin.")
        return redirect("accounts:enter_otp", username, otp.id)


class SetNewPasswordsView(View):
    template_name = 'accounts/set_new_password.html'

    def get(self, request, username, verification_code):
        user = User.objects.filter(username=username).first()
        if not user:
            messages.warning(request, "User not found.")
            return redirect("accounts:reset_password")
        if user.password_reset_verification_code != verification_code:
            messages.warning(request, "Sorry, the link has expired.")
            return redirect("accounts:reset_password")

        return render(request, self.template_name)

    def post(self, request, username, verification_code):
        user = User.objects.filter(username=username).first()
        if not user:
            messages.warning(request, "User not found.")
            return redirect("accounts:reset_password")
        if user.password_reset_verification_code != verification_code:
            messages.warning(request, "Sorry, the link has expired.")
            return redirect("accounts:reset_password")

        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")
        if password != confirm_password:
            messages.error(request, "Passwords do not match.")

app/accounts/templates/accounts/base_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'images/site-logo.png' %}" type="image/svg">
    <title>{% block page_title %}Home{%endblock%}</title>
</head>

<body class="accounts-body"> 
    {% block content %}{% endblock %}
    <div class="form-group mt-5">
        <p class="text text-center">Copyright &copy;
            <script>document.write(new Date().getFullYear())</script> All Rights Reserved
        </p>
    </div>
</body>

</html>

app/accounts/templates/accounts/enter_otp.html
{% extends 'templates/accounts/base_template.html' %}
{% block pagetitle %}Login{% endblock %}

{% load static %}

{% block content %}
<div class="col-md-10 mx-auto col-11">
    <div class="col-md-12 col-12 mx-auto">
        <div class="row">
            <div class="col-md-6 col-lg-3 mx-auto">
                <div class="card-shadow">
                    {% for message in messages %}
                    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                        {{message}}
                    </div>
                    {% endfor %}

                    <form method="POST" class="needs-validation" novalidate>
                        {% csrf_token %}
                        <p class="text text-center">A PIN has been sent to your number: <span
                                class="badge bg-primary">{{otp.address}}</span></p>
                        <div class="d-flex">
                            <div class="col-10">
                                <input type="text" name="pin" class="form-control" placeholder="Enter OTP" required>
                                <div class="invalid-feedback">
                                    Please enter your code here.
                                </div>
                            </div>
                            <div class="col-2 d-flex">
                                <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                    <form class="{% url 'accounts:reset_password' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="username" value="{{username}}">
                        <div class="form-group my-2">
                            Your PIN expires in <span class="count-down text-info" data-start="{{otp.get_time_left}}"
                                data-target="#resend-btn">{{otp.duration}}</span> minute(s).
                            <button type="submit" class="btn btn-sm btn-primary" disabled
                                id="resend-btn">Resend</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/accounts/templates/accounts/login.html
{% extends 'templates/accounts/base_template.html' %}
{% block page_title %}Login{% endblock %}

{% load static %}

{% block content %}
<div
    class="col-md-6 col-lg-3 card-shadow col-10  p-5 bg-white mx-auto h-100 mt-5 d-flex justify-content-center align-items-center">
    <section>
        <form class="form needs-validation" method="POST" novalidate>
            {% csrf_token %}
            <img class="mx-auto d-block" src="{% static 'images/logo.png' %}" alt="Site Logo" height="100">
            <h6 class="text text-center my-3 font-weight-normal">Please sign in.</h6>

            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}

            <div class="form-group my-3">
                <input type="email" id="email_address" name="email_address" value="{{email_address}}" class="form-control py-2"
                    placeholder="Email Address" required autofocus>
                <div class="invalid-feedback">
                    Please a valid email address.
                </div>
            </div>

            <div class="form-group my-3">
                <input type="password" id="password" name="password" value="{{password}}" class="form-control  py-2"
                    placeholder="Password" required>
                <div class="invalid-feedback">
                    Please enter your password.
                </div>
            </div>

            <div class="form-group d-flex justify-content-center my-3">
                <button class="btn btn-sm btn-primary" type="submit">Sign in</button>
            </div>
        </form>

        <p class="m-0 p-0 text-primary text-center">Forgot your password?</p>
        <p class="m-0 p-0 text-center"><a href="{% url 'accounts:reset_password' %}"
                class="btn btn-sm btn-outline-primary">Reset password.</a></p>
    </section>
</div>
{% endblock %}

app/accounts/templates/accounts/profile.html
{% extends 'templates/dashboard/base.html' %}
{% block pagetitle %}Profile{%endblock%}
{% block active-sidebar-item-id %}my-profile{%endblock%}

{% block breadcrum %}
<a href="/" class="item">Dashboard <i class="bi bi-chevron-compact-right"></i></a>
<a class="item">Profile <i class="bi bi-chevron-compact-right"></i></a>
{% endblock %}

{% block content %}
<div class="col-md-10 mx-auto col-11">
    <div class="col-md-12 col-12 mx-auto">
        <h4 class="mt-2">Hi, {{request.user.display_name}} <i>!</i></h4>

        {% if not request.user.phone_verified %}
        <div class="col-xl-6">
            <div class="alert alert-danger alert-dismissible fade show py-3 mt-1" role="alert">
                <strong>Attention!</strong>
                <span>Please your number has not been verified. You will not be able to receive sms notifications if it
                    is not verified.
                    <form action="{% url 'accounts:send_otp' %}" class="d-inline" method="post">
                        {% csrf_token %}
                        Click <button type="submit" class="btn btn-sm btn-danger">here</button> to
                        verified now.
                    </form>
                </span>
            </div>
        </div>
        {% endif %}

        <div class="row">
            <div class="col-md-6">
                <div class="card-shadow">
                    <div class="d-flex justify-content-center">
                        <img src="{{request.user.profile_picture}}" class="profile-img" height="100"
                            alt="{{request.user.get_name}}">
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label class="d-flex justify-content-center align-items-center" for="photo"
                            style="background-color: #f0f0f0; height: 5em; width: 100%; border: 1px dashed gray; cursor: pointer;">
                            <p class="chosen-file-name">Upload New Image</p>
                            <input type="file" class="file-input form-control d-none" name="photo" id="photo">
                        </label>
                        <p class="text-end"><button type="submit" class="btn my-2 btn-sm btn-primary">Save</button></p>
                    </form>
                </div>
                <div class="card-shadow">
                    <div class="col-12">
                        <h5 class="mt-2">Change Password</h5>
                    </div>
                    <form action="{% url 'accounts:change_password' %}" method="post" class="needs-validation"
                        novalidate>
                        {% csrf_token %}
                        <div class="form-group col-md-12 mb-3">
                            <label for="password">Current Password</label>
                            <input type="password" class="form-control" name="current_password" required>
                        </div>

                        <div class="col-12 row">
                            <div class="form-group col-md-6 mb-3">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" name="new_password" required minlength="5">
                                <div class="invalid-feedback">
                                    Please password should have a minimum 5 characters.
                                </div>
                            </div>

                            <div class="form-group col-md-6 mb-3">
                                <label for="confirm_password">Confirm Password</label>
                                <input type="password" class="form-control" name="confirm_password" required>
                                <div class="invalid-feedback">
                                    Please enter a valid password.
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-12 mb-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card-shadow">
                    <div class="col-12">
                        <h5 class="mt-2">Biography</h5>
                    </div>
                    <form action="" method="post" class="needs-validation" novalidate>
                        {% csrf_token %}
                        <div class="col-12 row">
                            <div class="form-group col-md-12 mb-3">
                                <label for="email_address">Username</label>
                                <input type="text" class="form-control" type="text" disabled
                                    value="{{request.user.username}}">
                            </div>

                            <div class="form-group col-md-12 mb-3">
                                <label for="title">Title</label>
                                <input type="text" class="form-control" type="text" name="title"
                                    value="{{request.user.title}}">
                                <div class="invalid-feedback" required>
                                    Please enter a valid title.
                                </div>
                            </div>

                            <div class="form-group col-md-12 mb-3">
                                <label for="surname">Surname</label>
                                <input type="text" class="form-control" name="surname" value="{{request.user.surname}}"
                                    required>
                                <div class="invalid-feedback">
                                    Please enter a valid surname.
                                </div>
                            </div>

                            <div class="form-group col-md-12 mb-3">
                                <label for="other_names">Other Names</label>
                                <input type="text" class="form-control" name="other_names"
                                    value="{{request.user.other_names}}" required>
                                <div class="invalid-feedback">
                                    Please enter a valid surname.
                                </div>
                            </div>

                            <div class="form-group col-md-12 mb-3">
                                <label for="email_address">Email Address</label>
                                <input class="form-control" name="email_address" type="email"
                                    value="{{request.user.email_address}}" required>
                                <div class="invalid-feedback">
                                    Please enter a valid email address.
                                </div>
                            </div>

                            <div class="form-group col-md-12 mb-3">
                                <label for="phone">Phone
                                    {% if request.user.phone_verified %}
                                    <span class="text text-success"><i class="bi bi-check-circle"></i> verified</span>
                                    {% else %}
                                    <span class="text text-danger"><i class="bi bi-x-lg"></i> not verified</span>
                                    {% endif %}
                                </label>
                                <i class="bi-bi-circle"></i>
                                {% if request.user.phone_verified %}
                                <p class="p-0 m-0 text-primary">
                                    <small>You may contact the administrator to change your
                                        verified phone number.
                                    </small>
                                </p>
                                {% endif %}
                                <input {% if request.user.phone_verified %} disabled {% endif %} name="phone"
                                    type="text" class="form-control" value="{{request.user.phone}}" required
                                    minlength="10" maxlength="10">
                                <div class="invalid-feedback">
                                    Please enter a valid 10-digit phone number.
                                </div>
                            </div>

                            <div class="form-group col-md-12 mb-3">
                                <label for="region">Region</label>
                                <select name="region" id="region" class="form-control" required>
                                    <option value="">Select Region</option>
                                    {% for region in regions %}
                                    <option value="{{region}}"
                                        {% if request.user.region == region %}selected{% endif %}>{{region}}</option>
                                    {% endfor %}
                                </select>
                                <div class="invalid-feedback">
                                    Please enter a valid 10-digit phone number.
                                </div>
                            </div>

                            <div class="form-group col-md-12 mb-3">
                                <label for="gender">Gender</label>
                                <select name="gender" id="gender" class="form-control" required>
                                    <option>---Select----</option>
                                    <option value="Male" {% if request.user.gender == 'Male' %}selected {% endif %}>Male</option>
                                    <option value="Female"{% if request.user.gender == 'Female' %}selected {% endif %}>Female</option>
                                </select>
                                <div class="invalid-feedback">
                                    Please enter a valid 10-digit phone number.
                                </div>
                            </div>

                            <div class="form-group col-12 mb-3">
                                <label for="display_name">Display Name</label>
                                <p class="p-0 m-0 text-primary"><small><i class="bi bi-info-circle"></i>
                                        This is how your name will be displayed on the documents sign.</small></p>
                                <input type="text" class="form-control" name="display_name"
                                    placeholder="e.g., ANTHONY ARTHUR/SUPT" value="{{request.user.display_name}}"
                                    required>
                                <div class="invalid-feedback">
                                    Please enter a valid name
                                </div>
                            </div>

                            <div class="form-group col-12 mb-3">
                                <label for="position">Position/Role</label>
                                <input type="text" class="form-control" name="position"
                                    placeholder="e.g., SUPT/PENSIONS" value="{{request.user.position}}" required>
                                <div class="invalid-feedback">
                                    Please enter a valid name
                                </div>
                            </div>

                            <div class="form-group col-12 mb-3 d-flex justify-content-end">
                                <button type="submit" class="btn btn-sm btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="form-group col-12 mb-3">
            <button type="button" class="btn btn-sm btn-primary" onclick="history.back()"><i
                    class="bi bi-arrow-left"></i> Back</button>
        </div>
    </div>
</div>
</div>
{%endblock%}

app/accounts/templates/accounts/verify_phone.html
{% extends 'templates/dashboard/base.html' %}
{% block pagetitle %}Profile{%endblock%}
{% block active-sidebar-item-id %}my-profile{%endblock%}

{% block breadcrum %}
<a href="/" class="item">Dashboard <i class="bi bi-chevron-compact-right"></i></a>
<a class="item">Profile <i class="bi bi-chevron-compact-right"></i></a>
{% endblock %}

{% block content %}
<div class="col-md-10 mx-auto col-11">
    <div class="col-md-12 col-12 mx-auto">
        <div class="row">
            <div class="col-md-6 col-lg-5 mx-auto">
                <div class="card-shadow">
                    <form method="POST" class="needs-validation" novalidate>
                        {% csrf_token %}
                        <p class="text text-center">A PIN has been sent to your number: <span
                                class="badge bg-primary">{{otp.address}}</span></p>
                        <div class="d-flex">
                            <div class="col-10">
                                <input type="text" name="pin" class="form-control" placeholder="Enter OTP" required>
                                <div class="invalid-feedback">
                                    Please enter your code here.
                                </div>
                            </div>
                            <div class="col-2 d-flex">
                                <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                    <form class="{% url 'accounts:send_otp' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group my-2">
                            Your PIN expires in <span class="count-down text-info" data-start="{{otp.get_time_left}}"
                                data-target="#resend-btn">{{otp.duration}}</span> minute(s).
                            <button type="submit" class="btn btn-sm btn-primary" disabled
                                id="resend-btn">Resend</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}